add commit
yossdev/mypoints-admin pull request #5
Opened 2021-12-19 11:35 UTC by MohammadWawan

2021-12-19 13:35 UTC, yossdev approved these changes
oke, untuk next message lebih mendekripsikan apa yang di commit

2021-12-19 13:39 UTC, yossdev requested changes
kurang page 404, sekalian perbaiki message commit

2021-12-19 13:54 UTC, yossdev requested changes

2021-12-19 13:54 UTC, yossdev commented on src/App.js
> +import History from "./pages/History/history"
ini diubah kalau pakai folder file nya jdin index.js

2021-12-19 15:22 UTC, MohammadWawan commented on src/App.js
> +import History from "./pages/History/history"
sudah ku benahin tinggal yg atomic folder belum

2021-12-19 15:23 UTC, MohammadWawan commented
monggo di cek kembali

2021-12-19 15:26 UTC, yossdev requested changes

2021-12-19 15:26 UTC, yossdev commented on src/App.js
> +
route 404 nya mana?

2021-12-19 15:38 UTC, MohammadWawan commented on src/App.js
> +
udah ku tambahkan lagi. karena tadi masih belum bisa onclick ke dashboard

2021-12-19 19:12 UTC, yossdev requested changes
Perbaiki lg wan, ikuti repo client

2021-12-19 19:12 UTC, yossdev commented on src/App.js
> +          <Route path="/notfound" exact element={<NotFound/>}></Route>
kok ada route ini?

2021-12-20 07:31 UTC, MohammadWawan commented on src/App.js
> +          <Route path="/notfound" exact element={<NotFound/>}></Route>
oke ku perbaiki sekarang

2021-12-20 07:43 UTC, MohammadWawan commented on src/App.js
> +          <Route path="/notfound" exact element={<NotFound/>}></Route>
monggo coba dicek kembali. kalau ada yang kurang di comment lagi ya.

2021-12-20 12:11 UTC, yossdev approved these changes
oke aman untuk sekarang

2021-12-20 12:58 UTC, adzanfsw approved these changes

2021-12-20 14:51 UTC, merged