change & add code
yossdev/mypoints-admin pull request #6
Opened 2021-12-20 16:01 UTC by MohammadWawan

2021-12-20 19:55 UTC, yossdev requested changes

2021-12-20 19:55 UTC, yossdev commented on tailwind.config.js
>  }
ikutin repo client confignya

2021-12-20 22:48 UTC, adzanfsw commented on tailwind.config.js
>  }
tinggal copy paste yg config agent aja wan

2021-12-21 08:52 UTC, MohammadWawan commented on tailwind.config.js
>  }
siap. kemarin aku nunggu yang agent soalnya. ini mau di update

2021-12-21 10:10 UTC, yossdev requested changes
Oke, kurang page error. Sama click dropdown di dashboard masih bermasalah

2021-12-22 07:22 UTC, MohammadWawan commented
page error sudah aku buat.
next progress membuat web design page lainnya.

2021-12-22 09:14 UTC, adzanfsw approved these changes

2021-12-22 15:57 UTC, yossdev requested changes
masih ada yg perlu diperbaiki

2021-12-22 15:57 UTC, yossdev commented on src/App.js
> +        <Route path="error" element={<PageError />}></Route>
buat komponen error aja ga perlu dijadiin route

2021-12-23 09:04 UTC, yossdev approved these changes

2021-12-23 09:14 UTC, merged